name: Build & Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
      NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY }}
      NEXT_PUBLIC_ALGOLIA_WRITE_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_WRITE_API_KEY }}
      NEXT_PUBLIC_ALGOLIA_INDEX_NAME: ${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build Docker image with build args
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_ALGOLIA_APP_ID=${{ env.NEXT_PUBLIC_ALGOLIA_APP_ID }} \
            --build-arg NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=${{ env.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY }} \
            --build-arg NEXT_PUBLIC_ALGOLIA_WRITE_API_KEY=${{ env.NEXT_PUBLIC_ALGOLIA_WRITE_API_KEY }} \
            --build-arg NEXT_PUBLIC_ALGOLIA_INDEX_NAME=${{ env.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }} \
            -t ghcr.io/${{ github.repository_owner }}/webx-beyond:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/webx-beyond:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/webx-beyond:latest \
            -t ghcr.io/${{ github.repository_owner }}/webx-beyond:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/webx-beyond:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/webx-beyond:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/webx-beyond:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/webx-beyond:latest
